# Generated by Django 4.2.7 on 2025-08-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_passenger_wallet_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="earnings",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
