# Generated by Django 4.2.7 on 2025-08-16 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("address", models.CharField(max_length=255)),
                ("postcode", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Ride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_time", models.DateTimeField(auto_now_add=True)),
                ("pickup_time", models.DateTimeField(blank=True, null=True)),
                ("dropoff_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("ACCEPTED", "Accepted"),
                            ("PICKED_UP", "Picked Up"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="REQUESTED",
                        max_length=20,
                    ),
                ),
                (
                    "ride_type",
                    models.CharField(
                        choices=[
                            ("STANDARD", "Standard"),
                            ("POOL", "Pool"),
                            ("LUXURY", "Luxury"),
                        ],
                        default="STANDARD",
                        max_length=20,
                    ),
                ),
                (
                    "fare",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("distance", models.FloatField(default=0)),
                ("rating", models.IntegerField(blank=True, null=True)),
                ("surge_multiplier", models.FloatField(default=1.0)),
                ("payment_method", models.CharField(default="card", max_length=50)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.driver",
                    ),
                ),
                (
                    "dropoff_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dropoff_rides",
                        to="rides.location",
                    ),
                ),
                (
                    "passenger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.passenger",
                    ),
                ),
                (
                    "pickup_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pickup_rides",
                        to="rides.location",
                    ),
                ),
            ],
        ),
    ]
